#!/usr/bin/env bash
set -euo pipefail

echo "========================================="
echo "  Galileo Tooling Setup"
echo "========================================="
echo ""

# Resolve repo root (works from any subdirectory)
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -f "$REPO_DIR/env.sample" ]; then
  echo "Error: setup.sh must be run from within the galileo-tooling repo."
  exit 1
fi

echo "Repo: $REPO_DIR"
echo ""

# --- 2. Environment variables ---
ENV_FILE="$REPO_DIR/.env"

# Load existing .env if present
if [ -f "$ENV_FILE" ]; then
  echo "Found existing $ENV_FILE, loading values..."
  set -a
  source "$ENV_FILE"
  set +a
fi

# Helper: prompt only if not already set
prompt_if_empty() {
  local var_name="$1"
  local prompt_text="$2"
  local current_value="${!var_name:-}"
  if [ -n "$current_value" ]; then
    echo "  $var_name: already set"
  else
    read -rp "  $prompt_text: " value
    printf -v "$var_name" '%s' "$value"
  fi
}

echo ""
echo "========================================="
echo "  API Tokens (leave blank to skip)"
echo "========================================="
echo ""

prompt_if_empty SENTRY_AUTH_TOKEN "Sentry auth token"
prompt_if_empty SHORTCUT_API_TOKEN "Shortcut API token"
prompt_if_empty LOGZIO_API_TOKEN "Logz.io API token"
if [ -n "${LOGZIO_API_TOKEN:-}" ]; then
  prompt_if_empty LOGZIO_ACCOUNT_REGION "Logz.io account region [us]"
  LOGZIO_ACCOUNT_REGION="${LOGZIO_ACCOUNT_REGION:-us}"
fi
prompt_if_empty CLICKHOUSE_HOST "ClickHouse host"
if [ -n "${CLICKHOUSE_HOST:-}" ]; then
  prompt_if_empty CLICKHOUSE_USER "ClickHouse user"
  prompt_if_empty CLICKHOUSE_PASSWORD "ClickHouse password"
fi

cat > "$ENV_FILE" <<ENVEOF
# Galileo Tooling — Environment Variables
# Generated by setup.sh on $(date +%Y-%m-%d)

# Sentry
SENTRY_AUTH_TOKEN='${SENTRY_AUTH_TOKEN:-}'

# Shortcut
SHORTCUT_API_TOKEN='${SHORTCUT_API_TOKEN:-}'

# Logz.io
LOGZIO_API_TOKEN='${LOGZIO_API_TOKEN:-}'
LOGZIO_ACCOUNT_REGION='${LOGZIO_ACCOUNT_REGION:-}'

# ClickHouse
CLICKHOUSE_HOST='${CLICKHOUSE_HOST:-}'
CLICKHOUSE_USER='${CLICKHOUSE_USER:-}'
CLICKHOUSE_PASSWORD='${CLICKHOUSE_PASSWORD:-}'
ENVEOF

echo ""
echo "Wrote $ENV_FILE"

# --- 3. Install skills ---
echo ""
echo "========================================="
echo "  Installing Skills"
echo "========================================="
echo ""

if command -v npx &> /dev/null; then
  echo "Installing Galileo skills via Vercel skills framework..."
  npx skills add "$REPO_DIR/skills" --all || echo "Warning: skills install failed. You can retry with: npx skills add $REPO_DIR/skills"
else
  echo "npx not found — skipping skills install."
  echo "Install Node.js, then run: npx skills add $REPO_DIR/skills"
fi

# --- 4. Symlink shared rules into Claude Code ---
echo ""
echo "========================================="
echo "  Configuring Claude Code"
echo "========================================="
echo ""

CLAUDE_DIR="$HOME/.claude"
mkdir -p "$CLAUDE_DIR"

# Symlink shared memory
if [ -d "$REPO_DIR/memory" ] && [ "$(ls -A "$REPO_DIR/memory" 2>/dev/null)" ]; then
  if [ -L "$CLAUDE_DIR/shared-memory" ]; then
    rm "$CLAUDE_DIR/shared-memory"
  fi
  ln -sf "$REPO_DIR/memory" "$CLAUDE_DIR/shared-memory"
  echo "Linked shared memory → $CLAUDE_DIR/shared-memory"
else
  echo "No shared memory files yet, skipping symlink."
fi

# Symlink shared rules
if [ -d "$REPO_DIR/rules" ] && [ "$(ls -A "$REPO_DIR/rules" 2>/dev/null)" ]; then
  if [ -L "$CLAUDE_DIR/shared-rules" ]; then
    rm "$CLAUDE_DIR/shared-rules"
  fi
  ln -sf "$REPO_DIR/rules" "$CLAUDE_DIR/shared-rules"
  echo "Linked shared rules → $CLAUDE_DIR/shared-rules"
else
  echo "No shared rules yet, skipping symlink."
fi

# --- 5. Summary ---
echo ""
echo "========================================="
echo "  Setup Complete"
echo "========================================="
echo ""
echo "  Repo:    $REPO_DIR"
echo "  Env:     $ENV_FILE"
echo ""
