#!/usr/bin/env bash
set -euo pipefail

echo "========================================="
echo "  Galileo Tooling Setup"
echo "========================================="
echo ""

# Resolve repo root (works from any subdirectory)
REPO_DIR="$(cd "$(dirname "$0")" && pwd)"

if [ ! -f "$REPO_DIR/env.sample" ]; then
  echo "Error: setup.sh must be run from within the galileo-tooling repo."
  exit 1
fi

echo "Repo: $REPO_DIR"
echo ""

# --- Load existing .env if present ---
ENV_FILE="$REPO_DIR/.env"

if [ -f "$ENV_FILE" ]; then
  echo "Found existing $ENV_FILE, loading values..."
  set -a
  source "$ENV_FILE"
  set +a
fi

# Helper: prompt only if not already set
prompt_if_empty() {
  local var_name="$1"
  local prompt_text="$2"
  local current_value="${!var_name:-}"
  if [ -n "$current_value" ]; then
    echo "  $var_name: already set"
  else
    read -rp "  $prompt_text: " value
    printf -v "$var_name" '%s' "$value"
  fi
}

# =========================================
#  API Tokens (leave blank to skip)
# =========================================
echo ""
echo "========================================="
echo "  Sentry (leave blank to skip)"
echo "========================================="
echo "  Create a token at: https://sentry.io/settings/account/api/auth-tokens/"
echo "  Required scopes: event:read, org:read, project:read, team:read, issue:read"
echo ""
prompt_if_empty SENTRY_ACCESS_TOKEN "Sentry auth token"

echo ""
echo "========================================="
echo "  Logz.io (leave blank to skip)"
echo "========================================="
echo "  Get the API key from 1Password (ask Shuai Shao for access)"
echo ""
prompt_if_empty LOGZIO_API_KEY "Logz.io API key"
if [ -n "${LOGZIO_API_KEY:-}" ]; then
  prompt_if_empty LOGZIO_REGION "Logz.io region [us]"
  LOGZIO_REGION="${LOGZIO_REGION:-us}"
fi

echo ""
echo "========================================="
echo "  Slack (leave blank to skip)"
echo "========================================="
echo "  See mcp/slack.md for full setup instructions"
echo ""
prompt_if_empty SLACK_BOT_TOKEN "Slack bot token (xoxb-...)"
if [ -n "${SLACK_BOT_TOKEN:-}" ]; then
  prompt_if_empty SLACK_TEAM_ID "Slack team ID (T...)"
fi

echo ""
echo "========================================="
echo "  ClickHouse (leave blank to skip)"
echo "========================================="
echo ""
prompt_if_empty CLICKHOUSE_HOST "ClickHouse host"
if [ -n "${CLICKHOUSE_HOST:-}" ]; then
  prompt_if_empty CLICKHOUSE_USER "ClickHouse user"
  prompt_if_empty CLICKHOUSE_PASSWORD "ClickHouse password"
fi

echo ""
echo "========================================="
echo "  Shortcut (leave blank to skip)"
echo "========================================="
echo ""
prompt_if_empty SHORTCUT_API_TOKEN "Shortcut API token"

# --- Write .env ---
cat > "$ENV_FILE" <<ENVEOF
# Galileo Tooling — Environment Variables
# Generated by setup.sh on $(date +%Y-%m-%d)

# Sentry
SENTRY_ACCESS_TOKEN='${SENTRY_ACCESS_TOKEN:-}'

# Logz.io
LOGZIO_API_KEY='${LOGZIO_API_KEY:-}'
LOGZIO_REGION='${LOGZIO_REGION:-}'

# Slack
SLACK_BOT_TOKEN='${SLACK_BOT_TOKEN:-}'
SLACK_TEAM_ID='${SLACK_TEAM_ID:-}'

# ClickHouse
CLICKHOUSE_HOST='${CLICKHOUSE_HOST:-}'
CLICKHOUSE_USER='${CLICKHOUSE_USER:-}'
CLICKHOUSE_PASSWORD='${CLICKHOUSE_PASSWORD:-}'

# Shortcut
SHORTCUT_API_TOKEN='${SHORTCUT_API_TOKEN:-}'
ENVEOF

echo ""
echo "Wrote $ENV_FILE"

# --- Generate / merge .mcp.json from template ---
echo ""
echo "========================================="
echo "  Configuring MCP Servers"
echo "========================================="
echo ""

MCP_FILE="$REPO_DIR/.mcp.json"
MCP_TEMPLATE="$REPO_DIR/mcp/mcp.template.json"

# Substitute env vars into template, then use node to drop unconfigured
# servers and merge with any existing .mcp.json
node -e "
const fs = require('fs');
const [mcpFile, templateFile] = process.argv.slice(1);

// Read template and substitute \${VAR} placeholders from env
let raw = fs.readFileSync(templateFile, 'utf8');
raw = raw.replace(/\\\$\{(\w+)\}/g, (_, key) => process.env[key] || '');
const template = JSON.parse(raw);

// Drop servers where any env value is empty
for (const [name, server] of Object.entries(template.mcpServers)) {
  const envVals = Object.values(server.env || {});
  if (envVals.some(v => !v)) {
    delete template.mcpServers[name];
  }
}

// Load existing .mcp.json if present
let existing = { mcpServers: {} };
if (fs.existsSync(mcpFile)) {
  try {
    existing = JSON.parse(fs.readFileSync(mcpFile, 'utf8'));
    if (!existing.mcpServers) existing.mcpServers = {};
    console.log('  Loaded existing ' + mcpFile);
  } catch (e) {
    console.log('  Warning: could not parse existing .mcp.json, starting fresh');
  }
}

// Merge: existing servers take priority (don't overwrite)
let added = [];
let skipped = [];
for (const [name, server] of Object.entries(template.mcpServers)) {
  if (existing.mcpServers[name]) {
    skipped.push(name + ' (already configured)');
  } else {
    existing.mcpServers[name] = server;
    added.push(name);
  }
}

for (const s of added) console.log('  + ' + s);
for (const s of skipped) console.log('  ~ ' + s);

if (Object.keys(existing.mcpServers).length > 0) {
  fs.writeFileSync(mcpFile, JSON.stringify(existing, null, 2) + '\n');
  console.log('');
  console.log('  Wrote ' + mcpFile);
  console.log('');
  console.log('  To use in your service repos, copy or symlink:');
  console.log('    cp ' + mcpFile + ' ~/your-project/.mcp.json');
  console.log('    # or');
  console.log('    ln -sf ' + mcpFile + ' ~/your-project/.mcp.json');
} else {
  console.log('  No MCP tokens provided, skipping .mcp.json');
}
" "$MCP_FILE" "$MCP_TEMPLATE"

# --- Install skills ---
echo ""
echo "========================================="
echo "  Installing Skills"
echo "========================================="
echo ""

if command -v npx &> /dev/null; then
  echo "Installing Galileo skills via Vercel skills framework..."
  npx skills add "$REPO_DIR/skills" --all || echo "Warning: skills install failed. You can retry with: npx skills add $REPO_DIR/skills"
else
  echo "npx not found — skipping skills install."
  echo "Install Node.js, then run: npx skills add $REPO_DIR/skills"
fi

# --- Symlink shared rules into Claude Code ---
echo ""
echo "========================================="
echo "  Configuring Claude Code"
echo "========================================="
echo ""

CLAUDE_DIR="$HOME/.claude"
mkdir -p "$CLAUDE_DIR"

# Symlink shared memory
if [ -d "$REPO_DIR/memory" ] && [ "$(ls -A "$REPO_DIR/memory" 2>/dev/null)" ]; then
  if [ -L "$CLAUDE_DIR/shared-memory" ]; then
    rm "$CLAUDE_DIR/shared-memory"
  fi
  ln -sf "$REPO_DIR/memory" "$CLAUDE_DIR/shared-memory"
  echo "Linked shared memory → $CLAUDE_DIR/shared-memory"
else
  echo "No shared memory files yet, skipping symlink."
fi

# Symlink shared rules
if [ -d "$REPO_DIR/rules" ] && [ "$(ls -A "$REPO_DIR/rules" 2>/dev/null)" ]; then
  if [ -L "$CLAUDE_DIR/shared-rules" ]; then
    rm "$CLAUDE_DIR/shared-rules"
  fi
  ln -sf "$REPO_DIR/rules" "$CLAUDE_DIR/shared-rules"
  echo "Linked shared rules → $CLAUDE_DIR/shared-rules"
else
  echo "No shared rules yet, skipping symlink."
fi

# --- Summary ---
echo ""
echo "========================================="
echo "  Setup Complete"
echo "========================================="
echo ""
echo "  Repo:      $REPO_DIR"
echo "  Env:       $ENV_FILE"
if [ -f "$MCP_FILE" ]; then
echo "  MCP:       $MCP_FILE"
fi
echo ""
