#!/usr/bin/env bash
# Collect API tokens interactively, skipping any already set in .env
set -euo pipefail

REPO_DIR="${REPO_DIR:?REPO_DIR must be set}"
ENV_FILE="$REPO_DIR/.env"

# Load existing .env if present
if [ -f "$ENV_FILE" ]; then
  echo "Found existing $ENV_FILE, loading values..."
  set -a
  source "$ENV_FILE"
  set +a
fi

# Helper: prompt only if not already set
prompt_if_empty() {
  local var_name="$1"
  local prompt_text="$2"
  local current_value="${!var_name:-}"
  if [ -n "$current_value" ]; then
    echo "  $var_name: already set"
  else
    read -rp "  $prompt_text: " value
    printf -v "$var_name" '%s' "$value"
  fi
}

echo ""
echo "========================================="
echo "  Sentry (leave blank to skip)"
echo "========================================="
echo "  Create a token at: https://sentry.io/settings/account/api/auth-tokens/"
echo "  Required scopes: event:read, org:read, project:read, team:read, issue:read"
echo ""
prompt_if_empty SENTRY_ACCESS_TOKEN "Sentry auth token"

echo ""
echo "========================================="
echo "  Logz.io (leave blank to skip)"
echo "========================================="
echo "  Get the API key from 1Password (ask Shuai Shao for access)"
echo ""
prompt_if_empty LOGZIO_API_KEY "Logz.io API key"
if [ -n "${LOGZIO_API_KEY:-}" ]; then
  prompt_if_empty LOGZIO_REGION "Logz.io region [us]"
  LOGZIO_REGION="${LOGZIO_REGION:-us}"
fi

echo ""
echo "========================================="
echo "  Slack (leave blank to skip)"
echo "========================================="
echo "  See mcp/slack.md for full setup instructions"
echo ""
prompt_if_empty SLACK_BOT_TOKEN "Slack bot token (xoxb-...)"
if [ -n "${SLACK_BOT_TOKEN:-}" ]; then
  prompt_if_empty SLACK_TEAM_ID "Slack team ID (T...)"
fi

echo ""
echo "========================================="
echo "  ClickHouse (leave blank to skip)"
echo "========================================="
echo ""
prompt_if_empty CLICKHOUSE_HOST "ClickHouse host"
if [ -n "${CLICKHOUSE_HOST:-}" ]; then
  prompt_if_empty CLICKHOUSE_USER "ClickHouse user"
  prompt_if_empty CLICKHOUSE_PASSWORD "ClickHouse password"
fi

echo ""
echo "========================================="
echo "  Shortcut (leave blank to skip)"
echo "========================================="
echo ""
prompt_if_empty SHORTCUT_API_TOKEN "Shortcut API token"

echo ""
echo "========================================="
echo "  Coda (leave blank to skip)"
echo "========================================="
echo "  Create a token at: https://coda.io/account → API settings → Generate API token"
echo ""
prompt_if_empty CODA_API_KEY "Coda API key"

# Write .env
cat > "$ENV_FILE" <<ENVEOF
# Galileo Tooling — Environment Variables
# Generated by setup.sh on $(date +%Y-%m-%d)

# Sentry
SENTRY_ACCESS_TOKEN='${SENTRY_ACCESS_TOKEN:-}'

# Logz.io
LOGZIO_API_KEY='${LOGZIO_API_KEY:-}'
LOGZIO_REGION='${LOGZIO_REGION:-}'

# Slack
SLACK_BOT_TOKEN='${SLACK_BOT_TOKEN:-}'
SLACK_TEAM_ID='${SLACK_TEAM_ID:-}'

# ClickHouse
CLICKHOUSE_HOST='${CLICKHOUSE_HOST:-}'
CLICKHOUSE_USER='${CLICKHOUSE_USER:-}'
CLICKHOUSE_PASSWORD='${CLICKHOUSE_PASSWORD:-}'

# Shortcut
SHORTCUT_API_TOKEN='${SHORTCUT_API_TOKEN:-}'

# Coda
CODA_API_KEY='${CODA_API_KEY:-}'
ENVEOF

echo ""
echo "Wrote $ENV_FILE"
