import json
import logging
import os
import re

import httpx

log = logging.getLogger(__name__)

BASE_URL = "https://api.github.com"


def _client() -> httpx.AsyncClient:
    token = os.environ.get("GITHUB_TOKEN")
    if not token:
        raise RuntimeError("GITHUB_TOKEN environment variable is not set")
    return httpx.AsyncClient(
        base_url=BASE_URL,
        headers={
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        },
        timeout=30,
    )


async def _paginate(client: httpx.AsyncClient, url: str, *, max_pages: int = 100) -> list[dict]:
    results: list[dict] = []
    page = 0
    while url:
        if page >= max_pages:
            log.warning("Reached max_pages limit (%d), stopping pagination", max_pages)
            break
        log.info("GET %s", url)
        resp = await client.get(url)
        resp.raise_for_status()
        results.extend(resp.json())
        url = resp.links.get("next", {}).get("url")
        page += 1
    return results


async def get_authenticated_user() -> str:
    """Return the login of the user associated with the current GITHUB_TOKEN."""
    async with _client() as client:
        url = "/user"
        log.info("GET %s", url)
        resp = await client.get(url)
        resp.raise_for_status()
        return resp.json()["login"]


async def get_pr_metadata(owner: str, repo: str, pr_number: int) -> dict:
    async with _client() as client:
        url = f"/repos/{owner}/{repo}/pulls/{pr_number}"
        log.info("GET %s", url)
        resp = await client.get(url)
        resp.raise_for_status()
        return resp.json()


async def get_pr_comments(owner: str, repo: str, pr_number: int) -> list[dict]:
    async with _client() as client:
        url = f"/repos/{owner}/{repo}/issues/{pr_number}/comments?per_page=100"
        return await _paginate(client, url)


async def get_pr_review_comments(owner: str, repo: str, pr_number: int) -> list[dict]:
    async with _client() as client:
        url = f"/repos/{owner}/{repo}/pulls/{pr_number}/comments?per_page=100"
        return await _paginate(client, url)


SEVERITY_EMOJI = {
    "critical": "🔴",
    "major": "🟠",
    "minor": "🟡",
    "nit": "🔵",
}


def _comment_body(comment: dict) -> str:
    emoji = SEVERITY_EMOJI.get(comment["severity"], "")
    prefix = f"**{emoji} {comment['severity']}** ({comment['category']})"
    body = f"{prefix}: {comment['comment']}"
    if comment.get("suggestion"):
        body += f"\n\n```suggestion\n{comment['suggestion']}\n```"
    return body


def _format_review_body(review: dict) -> str:
    lines = [
        "> ⚠️ **This review was generated by an AI agent (Astra) and may contain mistakes."
        " Please verify all suggestions independently.**",
        "",
        f"**Verdict: {review['verdict']}** — {review['verdict_reason']}",
    ]

    pr_comments = [
        c for c in review.get("pr_comments", [])
        if c["severity"] != "praise"
    ]
    if pr_comments:
        lines.append("")
        lines.append("## General Comments")
        for c in pr_comments:
            emoji = SEVERITY_EMOJI.get(c["severity"], "")
            lines.append(f"- **{emoji} {c['severity']}** ({c['category']}): {c['comment']}")

    follow_ups = review.get("follow_ups", [])
    if follow_ups:
        lines.append("")
        lines.append("## Follow-ups")
        lines.append("Suggested follow-up work that could be tracked as Shortcut stories:")
        for f in follow_ups:
            lines.append(f"- `{f['path']}:{f['start_line']}-{f['end_line']}`: {f['description']}")

    return "\n".join(lines)


def _parse_diff_lines(diff_text: str) -> dict[str, set[int]]:
    """Parse a unified diff into {filepath: set_of_new_side_line_numbers}.

    Returns which line numbers (new/RIGHT side) are present in the diff
    for each file — i.e., lines that GitHub will accept for inline comments.
    """
    file_lines: dict[str, set[int]] = {}
    current_file: str | None = None
    new_line = 0
    in_hunks = False

    for raw_line in diff_text.split("\n"):
        if raw_line.startswith("diff --git"):
            parts = raw_line.split(" b/", 1)
            if len(parts) == 2:
                current_file = parts[1]
                file_lines[current_file] = set()
                in_hunks = False
            continue

        if current_file is None:
            continue

        if raw_line.startswith("@@"):
            match = re.search(r"\+(\d+)", raw_line)
            if match:
                new_line = int(match.group(1))
            in_hunks = True
            continue

        if not in_hunks:
            continue
        if raw_line.startswith(("---", "+++", "\\")):
            continue

        if raw_line.startswith("-"):
            pass
        else:
            file_lines[current_file].add(new_line)
            new_line += 1

    return file_lines


def _extract_comment_id(comment_url: str) -> int:
    """Extract the review comment ID from a GitHub URL.

    Supports REST API URLs (`.../pulls/comments/{id}`)
    and HTML URLs (`...#discussion_r{id}`).
    """
    m = re.search(r"pulls/comments/(\d+)", comment_url)
    if m:
        return int(m.group(1))
    m = re.search(r"#discussion_r(\d+)", comment_url)
    if m:
        return int(m.group(1))
    raise ValueError(f"Cannot extract comment ID from URL: {comment_url}")


async def _graphql(query: str, variables: dict, *, client: httpx.AsyncClient | None = None) -> dict:
    """Execute a GitHub GraphQL query."""
    async def _execute(c: httpx.AsyncClient) -> dict:
        resp = await c.post(
            "/graphql",
            json={"query": query, "variables": variables},
        )
        resp.raise_for_status()
        data = resp.json()
        if data.get("errors"):
            raise RuntimeError(f"GraphQL errors: {json.dumps(data['errors'])}")
        return data["data"]

    if client is not None:
        return await _execute(client)
    async with _client() as c:
        return await _execute(c)


async def publish_review(
    owner: str,
    repo: str,
    pr_number: int,
    commit_sha: str,
    review: dict,
    pr_node_id: str,
    diff_text: str,
) -> dict:
    body = _format_review_body(review)
    diff_lines = _parse_diff_lines(diff_text)

    # Split line comments into in-diff (batch) and out-of-diff (individual)
    threads: list[dict] = []
    individual_threads: list[dict] = []

    for c in review.get("line_comments", []):
        if c["severity"] == "praise":
            continue
        valid_lines = diff_lines.get(c["path"], set())
        thread: dict = {
            "path": c["path"],
            "line": c["end_line"],
            "side": "RIGHT",
            "body": _comment_body(c),
        }
        if c["start_line"] != c["end_line"] and c["start_line"] in valid_lines:
            thread["startLine"] = c["start_line"]
            thread["startSide"] = "RIGHT"
        if c["end_line"] in valid_lines:
            threads.append(thread)
        else:
            log.info(
                "Line %d not in diff, will add individually: %s",
                c["end_line"], c["path"],
            )
            individual_threads.append(thread)

    # Collect file-level comments (filter out praise)
    file_threads: list[dict] = []
    for c in review.get("file_comments", []):
        if c["severity"] == "praise":
            continue
        file_threads.append({
            "path": c["path"],
            "body": _comment_body(c),
        })

    log.info(
        "Publishing review via GraphQL (%d in-diff, %d out-of-diff, %d file)",
        len(threads), len(individual_threads), len(file_threads),
    )

    # Use a shared HTTP client for all GraphQL calls in this review
    async with _client() as client:
        # Step 1: Create pending review with in-diff line threads
        create_result = await _graphql(
            """
            mutation($input: AddPullRequestReviewInput!) {
                addPullRequestReview(input: $input) {
                    pullRequestReview { id }
                }
            }
            """,
            {
                "input": {
                    "pullRequestId": pr_node_id,
                    "commitOID": commit_sha,
                    "threads": threads,
                },
            },
            client=client,
        )
        review_id = create_result["addPullRequestReview"]["pullRequestReview"]["id"]
        log.info("Created pending review: %s", review_id)

        # Step 2: Add out-of-diff line comments individually
        for it in individual_threads:
            await _graphql(
                """
                mutation($input: AddPullRequestReviewThreadInput!) {
                    addPullRequestReviewThread(input: $input) {
                        thread { id }
                    }
                }
                """,
                {
                    "input": {
                        "pullRequestReviewId": review_id,
                        **it,
                    },
                },
                client=client,
            )
        if individual_threads:
            log.info("Added %d out-of-diff line comment(s)", len(individual_threads))

        # Step 3: Add file-level comments
        for ft in file_threads:
            await _graphql(
                """
                mutation($input: AddPullRequestReviewThreadInput!) {
                    addPullRequestReviewThread(input: $input) {
                        thread { id }
                    }
                }
                """,
                {
                    "input": {
                        "pullRequestReviewId": review_id,
                        "path": ft["path"],
                        "body": ft["body"],
                        "subjectType": "FILE",
                    },
                },
                client=client,
            )
        if file_threads:
            log.info("Added %d file-level comment(s)", len(file_threads))

        # Step 4: Submit the review
        submit_result = await _graphql(
            """
            mutation($input: SubmitPullRequestReviewInput!) {
                submitPullRequestReview(input: $input) {
                    pullRequestReview { url }
                }
            }
            """,
            {
                "input": {
                    "pullRequestReviewId": review_id,
                    "event": "COMMENT",
                    "body": body,
                },
            },
            client=client,
        )
        url = submit_result["submitPullRequestReview"]["pullRequestReview"]["url"]
        log.info("Review submitted: %s", url)

    # Step 5: Post responses to existing review comment threads
    comment_responses = review.get("comment_responses", [])
    if comment_responses:
        bot_user = await get_authenticated_user()
        existing_comments = await get_pr_review_comments(owner, repo, pr_number)

        # Build a map of comment_id -> set of users in that thread
        thread_users: dict[int, set[str]] = {}
        for ec in existing_comments:
            ec_id = ec["id"]
            ec_user = ec["user"]["login"]
            # Add user to the comment's own entry
            thread_users.setdefault(ec_id, set()).add(ec_user)
            # If this is a reply, also add user to the parent thread
            parent_id = ec.get("in_reply_to_id")
            if parent_id:
                thread_users.setdefault(parent_id, set()).add(ec_user)

        posted = 0
        async with _client() as client:
            for cr in comment_responses:
                comment_id = _extract_comment_id(cr["comment_url"])
                users_in_thread = thread_users.get(comment_id, set())
                if bot_user in users_in_thread:
                    log.info(
                        "Skipping reply to comment %d — %s already in thread",
                        comment_id, bot_user,
                    )
                    continue
                reply_url = f"/repos/{owner}/{repo}/pulls/{pr_number}/comments/{comment_id}/replies"
                log.info("POST %s", reply_url)
                resp = await client.post(reply_url, json={"body": cr["response"]})
                resp.raise_for_status()
                posted += 1
        log.info(
            "Posted %d comment response(s), skipped %d (already replied)",
            posted, len(comment_responses) - posted,
        )

    return submit_result


async def get_pr_diff(owner: str, repo: str, pr_number: int) -> str:
    async with _client() as client:
        url = f"/repos/{owner}/{repo}/pulls/{pr_number}"
        log.info("GET %s (diff)", url)
        resp = await client.get(
            url,
            headers={"Accept": "application/vnd.github.v3.diff"},
        )
        resp.raise_for_status()
        return resp.text
